# 2024-11-15

## Clock

I have enough parts printed to put the frame together and see if it will run.

I still have the issue that the escape wheel has an even number of teeth, I was hoping to tilt the balance
shaft over by rotating the frame upper part, so that the top pallet is out of position by half a tooth,
just to see if it works.

I also don't have any way of winding it, so at first I can rotate the escape wheel shaft by hand, then tape
some string to it.

I also don't have any way to attach a balance spring, so at first I will have to run it at low enough amplitude
that it doesn't ride up onto the curved backs of the pallets.

https://img.incoherency.co.uk/5707

 * tilting the top over (as pictured) *does* make it possible for it to work with even number of teeth
 * the screw heads on the pallets stick out too far so they foul with the escape wheel at even very small amplitudes
 * I could make it run at very small amplitudes by twisting the escape wheel shaft with my teeth

So:

 * make the pallet clamps sit outside the plane of the escape wheel, just have the working surfaces stick up/down
 * make some shaft collars

I went to balance the balance shaft by holding the frame on its side and letting the balance shaft rotate
in its pivots, but it is pretty well balanced already.

I'm not quite sure what to do about a balance spring. I rummaged in the big springs in the garage but they all
feel like they are way too stiff.

Maybe one of the tension springs with loops on the end?? That might be good because I have quite a lot of different
stiffnesses in approximately the same form factor, although they appear out of proportion with the rest of
the mechanism.

OK, I have shaft collars & new pallets now. I want to work out what is the actual angle offset required
between the pallets. Are they parallel, perpendicular, or something else?

Perpendicular seems to work a lot better than parallel.

I do have the problem that the "frictional rest" surface has too small radius, so it doesn't provide frictional
rest, the escape wheel just spins freely.

I think I need to have fewer teeth on the escape wheel in order to be able to make this work, and probably
want an odd number.

Or smaller pallets. Now that the clamping surface is away from the working plane I can actually make the
pallets quite a bit smaller. I'll try that first because they'll print quicker. And this time swing it back
and forth in CAD and check that it looks like it'll work.

Other things to design include:

 * balance spring attachment
 * light gate holder/attachment/disc/electronics
 * winding drum?

For the new pallet design I'll make the impulse face radial and the resting surface centred on the shaft.
Once that works we can look at whether the impulse face should be offset and whether the radius or centre
of the resting surface should change.

This is a good animation: https://redfernanimation.com/the-harrison-timekeeper-h4-escapement/ - it shows
that the pallets are parallel but offset, also the pallets are a lot smaller than the escape wheel teeth.

This is what I have now: https://img.incoherency.co.uk/5708

When one tooth escapes the next one impacts almost immediately. That is what you want in this case. In a normal
verge escapement that would lead to basically 0 amplitude, but in this case the escape wheel gets pushed back
by the rotating balance.

The escape wheel only has 45 teeth now.

Also, FreeCAD has made real progress on the topological naming thing. I have a bunch of features added after
the PolarPattern for the escape wheel teeth, and changing the number of teeth hasn't broken anything. Good.

I wonder if there is any benefit to the escape wheel being this big if it only has 45 teeth.

Now that I have an arrangement that I think will work, maybe I should try to add more teeth to the
escape wheel again?

75 teeth: https://img.incoherency.co.uk/5709

I think I ought to be able to get basically arbitrarily many teeth? As long as the back side of
the pallet fits in between the teeth.

95 teeth: https://img.incoherency.co.uk/5710

I'm going to print this and see how it works.

So next up is the balance spring attachment. Hilariously, I hardly have any room to attach it to anything.

I have bent a little hook in a spring that will allow me to attach it to the pallet clamp, but attaching it
to the pallet clamp means it's impossible to rotate it relative to the pallets, so probably I need
a mechanism on the frame that lets me rotate the other end around the axis of the shaft.

https://img.incoherency.co.uk/5711

And now I've bent the other into a straight line pretty perpendicular to the hook, so for starters if I just
make something that can hold it at about the right angle on the frame, that might help.

Pretty ridiculous but might do: https://img.incoherency.co.uk/5712

The spring is represented in blue, and the pointy end of it will get clamped in that hole, either
by a perpendicular screw, or a tapered pin or something.

I will need to use a different type of spring though, this is going to rub on itself and on the shaft which
will just waste energy.

https://img.incoherency.co.uk/5713

This actually works really well. With the escape wheel pushed back and out of the way it ticks back and forth
at about 0.2Hz, so 5 seconds per cycle, or 2.5 seconds per beat. It doesn't keep going for
particularly long, maybe the pivots want to be turned out of metal or something instead of 3d printed. But
we'll proceed.

Now move the escape wheel in, turn it with fingers, and see if it works?

It does sort of work but it loses energy quite quickly.

Frictional rest is rubbing against the adjacent tooth and bending the escape wheel!
That can't be right. I'll decrease the depthing.

Meh, not possible to decrease the depthing far enough to help.

Lol, the same problem exists in CAD. So this is why the gap between the escape wheel teeth needs to be large.

Not super clear but: https://img.incoherency.co.uk/5714

The tip of the impulse face has just pushed the nearest tooth out of the way, and the resting face
needs to be clear of the next tooth, but you can see it overlaps the resting face. We basically can only
have about half as many escape wheel teeth.

It looks fine in CAD with 55 teeth, printing this escape wheel now:

https://img.incoherency.co.uk/5715

Probably the pallets could be a bit closer together, but will give it a go as-is.
